version: 0.2
phases:
  install:
    commands:
      - echo "Install phase"
  build:
    commands:
      - echo "Zipping artifacts"
      - mkdir -p artifact
      - cp -r web appspec.yml scripts artifact/
artifacts:
  files:
    - '/*'
  base-directory: artifact
